# Generated by Django 3.2.7 on 2021-09-09 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabtrackerapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='user_id',
            new_name='user',
        ),
    ]
