# Generated by Django 3.2.7 on 2021-09-09 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabtrackerapi', '0002_rename_user_id_lesson_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routine',
            old_name='user_id',
            new_name='user',
        ),
    ]
