# Generated by Django 3.2.7 on 2021-09-10 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabtrackerapi', '0004_auto_20210909_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='routine_id',
            new_name='routine',
        ),
    ]
